import type { AgentRegistryEntry } from "../types/agent.js";

export const DEFAULT_AGENT_REGISTRY: AgentRegistryEntry[] = [
  { agentId: "build", displayName: "Build", role: "implementer", lanes: ["delivery", "migration"], configurable: false, mode: "primary", permission: "builder", prompt: "Implement code changes with tests and verification.", defaultProvider: "openai", defaultModel: "gpt-codex", defaultVariant: "default" },
  { agentId: "plan", displayName: "Plan", role: "architect", lanes: ["quick", "delivery", "migration"], configurable: false, mode: "primary", permission: "read_only", prompt: "Inspect the codebase and produce an implementation plan without mutating files.", defaultProvider: "openai", defaultModel: "gpt-5", defaultVariant: "high-reasoning" },
  { agentId: "general", displayName: "General", role: "quick", lanes: ["quick"], configurable: false, mode: "primary", permission: "standard", prompt: "Handle general bounded coding assistant tasks.", defaultProvider: "openai", defaultModel: "gpt-5", defaultVariant: "default" },
  { agentId: "quick", displayName: "Quick", role: "quick", lanes: ["quick"], configurable: false, mode: "primary", permission: "standard", prompt: "Handle fast, low-risk, bounded tasks.", defaultProvider: "openai", defaultModel: "gpt-5", defaultVariant: "default" },
  { agentId: "quick-agent", displayName: "Quick Agent", role: "quick", lanes: ["quick"], configurable: true, mode: "primary", permission: "standard", prompt: "Compatibility quick agent for existing DH run/session flows.", defaultProvider: "openai", defaultModel: "gpt-5", defaultVariant: "default" },
  { agentId: "coordinator", displayName: "Coordinator", role: "coordinator", lanes: ["delivery", "migration"], configurable: true, mode: "primary", permission: "read_only", prompt: "Route workflow stages and identify blockers.", defaultProvider: "openai", defaultModel: "gpt-5", defaultVariant: "default" },
  { agentId: "analyst", displayName: "Analyst", role: "analyst", lanes: ["delivery", "migration"], configurable: true, mode: "primary", permission: "read_only", prompt: "Analyze scope, assumptions, risks, and acceptance criteria.", defaultProvider: "anthropic", defaultModel: "claude-opus", defaultVariant: "high-reasoning" },
  { agentId: "architect", displayName: "Architect", role: "architect", lanes: ["delivery", "migration"], configurable: true, mode: "primary", permission: "read_only", prompt: "Design architecture, work items, sequencing, and validation.", defaultProvider: "anthropic", defaultModel: "claude-opus", defaultVariant: "high-reasoning" },
  { agentId: "implementer", displayName: "Implementer", role: "implementer", lanes: ["delivery", "migration"], configurable: true, mode: "primary", permission: "builder", prompt: "Implement assigned work items and record verification.", defaultProvider: "openai", defaultModel: "gpt-codex", defaultVariant: "default" },
  { agentId: "reviewer", displayName: "Reviewer", role: "reviewer", lanes: ["delivery", "migration"], configurable: true, mode: "primary", permission: "read_only", prompt: "Review changes for correctness, scope, risk, and tests.", defaultProvider: "openai", defaultModel: "gpt-5", defaultVariant: "tool-use-optimized" },
  { agentId: "tester", displayName: "Tester", role: "tester", lanes: ["delivery", "migration"], configurable: true, mode: "primary", permission: "read_only", prompt: "Verify acceptance criteria and report limitations.", defaultProvider: "openai", defaultModel: "gpt-5", defaultVariant: "default" }
];
