import {
  PARITY_CATEGORIES,
  PARITY_STATUSES,
  type ParityCategory,
  type ParityFeature,
  type ParityReport,
  type ParityStatus,
} from "../../../shared/src/types/parity.js";

export const OPENCODE_MISSING_COMMAND_SURFACES = [
  "web",
  "attach",
  "db",
  "github",
  "pr",
  "acp",
] as const;

const RECOMMENDED_NEXT_MILESTONE = "Milestone 12: Web/Desktop Decision";

const FEATURES: ParityFeature[] = [
  {
    category: "runtime",
    surface: "Runtime authority",
    opencodeSurface: ["server/session/tool runtime", "event stream", "permission decisions"],
    dhSurface: [
      "Rust-hosted ask/explain/trace lifecycle",
      "Rust-hosted quick/delivery/migrate lane lifecycle",
      "Rust-hosted direct run lifecycle",
      "TypeScript worker compatibility boundary",
    ],
    status: "supported",
    priority: "P0",
    missingCommandSurfaces: [],
    missingRuntimeCapabilities: ["OpenCode session/provider/MCP/tool lifecycle authority remains planned in later milestones"],
    nextMilestone: RECOMMENDED_NEXT_MILESTONE,
    notes: ["Rust is authoritative for first-wave knowledge commands and lane command launch/supervision."],
  },
  {
    category: "cli",
    surface: "CLI command surface",
    opencodeSurface: [
      "run",
      "serve",
      "web",
      "attach",
      "session",
      "export",
      "import",
      "providers",
      "models",
      "mcp",
      "agent",
      "plugin",
      "stats",
      "db",
      "github",
      "pr",
      "acp",
    ],
    dhSurface: [
      "run (rust-hosted)",
      "serve",
      "tui",
      "ask",
      "explain",
      "trace",
      "index",
      "doctor",
      "quick (rust-hosted)",
      "delivery (rust-hosted)",
      "migrate (rust-hosted)",
      "session",
      "export",
      "import",
      "stats",
      "providers",
      "models",
      "mcp",
      "agent",
      "plugin",
      "config",
      "semantic-cleanup",
      "operator-safe-maintenance",
    ],
    status: "partial",
    priority: "P0",
    missingCommandSurfaces: [...OPENCODE_MISSING_COMMAND_SURFACES],
    missingRuntimeCapabilities: ["web/attach/db/github/pr/acp command surfaces"],
    nextMilestone: RECOMMENDED_NEXT_MILESTONE,
    notes: ["DH now has run, session, provider/model, and local MCP lifecycle command surfaces."],
  },
  {
    category: "session",
    surface: "Session product lifecycle",
    opencodeSurface: ["session list", "session delete", "continue", "fork", "export", "import", "share", "stats"],
    dhSurface: ["session primitives", "workflow state", "SQLite repositories", "session list/show/delete/fork", "export/import", "stats"],
    status: "partial",
    priority: "P0",
    missingCommandSurfaces: [],
    missingRuntimeCapabilities: ["remote share service remains deferred", "advanced transcript portability remains limited"],
    nextMilestone: RECOMMENDED_NEXT_MILESTONE,
    notes: ["Session lifecycle commands exist; hosted share parity remains outside the local-first core."],
  },
  {
    category: "provider",
    surface: "Provider and model lifecycle",
    opencodeSurface: ["providers list/login/logout", "models", "models.dev refresh"],
    dhSurface: ["AI SDK provider registry", "providers list/login/logout/verify", "models list/refresh"],
    status: "partial",
    priority: "P0",
    missingCommandSurfaces: [],
    missingRuntimeCapabilities: ["provider-specific OAuth/account flows", "cloud account console surfaces"],
    nextMilestone: RECOMMENDED_NEXT_MILESTONE,
    notes: ["Local credential lifecycle, verification, and model refresh are exposed; cloud account surfaces remain out of core scope."],
  },
  {
    category: "mcp",
    surface: "MCP lifecycle",
    opencodeSurface: ["mcp add", "mcp list", "mcp auth", "mcp logout", "mcp debug", "OAuth callback"],
    dhSurface: [
      "MCP routing",
      "MCP auth status",
      "audit surfaces",
      "mcp list/add/auth/logout/debug local lifecycle",
    ],
    status: "partial",
    priority: "P1",
    missingCommandSurfaces: [],
    missingRuntimeCapabilities: ["OAuth callback handling", "runtime MCP server lifecycle", "MCP stdio tool execution"],
    nextMilestone: "Milestone 5: MCP Lifecycle",
    notes: ["Local command-based MCP lifecycle exists; stdio runtime and OAuth callback support remain open."],
  },
  {
    category: "tool",
    surface: "Tool runtime catalog",
    opencodeSurface: ["read", "write", "edit", "bash", "glob", "grep", "apply_patch", "task", "todo", "webfetch", "websearch", "lsp"],
    dhSurface: [
      "retrieval tools",
      "bridge tools",
      "audit/enforcement records",
      "core tool catalog",
      "validated tool runner",
      "permission-bound shell execution",
      "tool event streaming",
    ],
    status: "partial",
    priority: "P1",
    missingCommandSurfaces: [],
    missingRuntimeCapabilities: [
      "model tool-call loop integration",
      "interactive permission prompt UI",
      "full apply_patch execution",
      "webfetch/websearch tools",
      "LSP-backed tool implementations",
    ],
    nextMilestone: RECOMMENDED_NEXT_MILESTONE,
    notes: ["DH has a validated, audited core tool runner; provider model-loop integration remains separate."],
  },
  {
    category: "agent",
    surface: "Agent and subagent runtime",
    opencodeSurface: ["agent create", "agent list", "task subagent", "build/plan/general agents"],
    dhSurface: [
      "workflow lanes",
      "role registry",
      "team roles",
      "agent list/create",
      "built-in build/plan/general agents",
      "repo-local custom agents",
      "bounded task subagent runtime",
      "agent selection in run loop",
    ],
    status: "partial",
    priority: "P1",
    missingCommandSurfaces: [],
    missingRuntimeCapabilities: [
      "advanced multi-agent scheduler",
      "parallel subagent orchestration",
      "rich prompt-template inheritance",
    ],
    nextMilestone: RECOMMENDED_NEXT_MILESTONE,
    notes: ["DH exposes selectable built-in/custom agents and bounded task subagents; advanced scheduling remains planned."],
  },
  {
    category: "lsp",
    surface: "LSP graph augmentation",
    opencodeSurface: ["diagnostics", "hover", "definition", "references", "workspace symbols", "call hierarchy"],
    dhSurface: [
      "Rust structural graph",
      "semantic retrieval",
      "LSP service boundary",
      "lsp diagnostics CLI",
      "LSP tool wrappers",
      "live LSP retrieval augmentation",
    ],
    status: "partial",
    priority: "P2",
    missingCommandSurfaces: [],
    missingRuntimeCapabilities: [
      "long-lived LSP process supervision",
      "language server auto-install",
      "definition/reference/hover client wiring",
      "call hierarchy implementation",
    ],
    nextMilestone: RECOMMENDED_NEXT_MILESTONE,
    notes: ["Rust graph remains canonical; LSP evidence is live augmentation only."],
  },
  {
    category: "plugin",
    surface: "Plugin ecosystem",
    opencodeSurface: ["server hooks", "TUI hooks", "command hooks", "tool hooks", "chat hooks", "session hooks"],
    dhSurface: [
      "extension-state fingerprint",
      "drift reporting",
      "minimal plugin contract docs",
      "local plugin registry",
      "plugin list/add",
      "deterministic declarative hooks",
      "plugin timeout/error isolation",
    ],
    status: "partial",
    priority: "P2",
    missingCommandSurfaces: [],
    missingRuntimeCapabilities: [
      "executable JS/WASM plugin API",
      "TUI plugin hooks",
      "session/chat transform runtime integration",
      "remote/npm plugin installation",
    ],
    nextMilestone: RECOMMENDED_NEXT_MILESTONE,
    notes: ["Local declarative plugin hooks exist; executable plugin APIs remain intentionally deferred."],
  },
  {
    category: "server",
    surface: "Headless server and SDK",
    opencodeSurface: ["serve", "SDK client/server architecture"],
    dhSurface: ["local HTTP server", "SDK client", "health route", "run command route", "local bind password guard"],
    status: "partial",
    priority: "P2",
    missingCommandSurfaces: [],
    missingRuntimeCapabilities: ["WebSocket/event streaming", "complete session/provider/MCP APIs", "server lifecycle under Rust supervision"],
    nextMilestone: RECOMMENDED_NEXT_MILESTONE,
    notes: ["Local JSON HTTP server and SDK exist; streaming and full API coverage remain next server hardening work."],
  },
  {
    category: "tui",
    surface: "Terminal UI",
    opencodeSurface: ["OpenTUI interactive client", "attach"],
    dhSurface: [
      "tui command",
      "local server attach/start",
      "session list rendering",
      "prompt submission",
      "permission request rendering",
      "read-only fallback",
    ],
    status: "partial",
    priority: "P2",
    missingCommandSurfaces: ["attach"],
    missingRuntimeCapabilities: [
      "attach command",
      "WebSocket/event streaming",
      "interactive permission approval API",
      "model/agent switch dialogs",
      "session resume/fork/delete shortcuts",
      "TUI plugin hooks",
    ],
    nextMilestone: RECOMMENDED_NEXT_MILESTONE,
    notes: ["Dependency-free TUI MVP attaches to the server/SDK contract; richer streaming UI remains deferred."],
  },
  {
    category: "github",
    surface: "GitHub and PR automation",
    opencodeSurface: ["github", "pr import", "pr checkout"],
    dhSurface: [],
    status: "deferred",
    priority: "P3",
    missingCommandSurfaces: ["github", "pr"],
    missingRuntimeCapabilities: ["GitHub auth", "PR import/checkout workflow", "GitHub agent integration"],
    nextMilestone: "Milestone 12: GitHub/PR Automation",
    notes: ["This depends on session import/export and provider/tool runtime stability."],
  },
  {
    category: "packaging",
    surface: "Desktop/cloud console",
    opencodeSurface: ["desktop package", "console package", "cloud/provider account surfaces"],
    dhSurface: ["local CLI release assets"],
    status: "out_of_scope",
    priority: "P3",
    missingCommandSurfaces: [],
    missingRuntimeCapabilities: ["desktop app", "cloud console", "remote share service"],
    nextMilestone: "No milestone until local/server/TUI surfaces prove stable",
    notes: ["This is intentionally outside the first parity program."],
  },
];

export function buildOpenCodeParityReport(): ParityReport {
  return {
    source: "opencode-gap-roadmap",
    baseline: {
      dh: "v0.3.1-rc.7 / 506b0af",
      opencode: "dev / 903d81819",
    },
    categories: PARITY_CATEGORIES,
    statuses: PARITY_STATUSES,
    features: FEATURES.map((feature) => ({
      ...feature,
      opencodeSurface: [...feature.opencodeSurface],
      dhSurface: [...feature.dhSurface],
      missingCommandSurfaces: [...feature.missingCommandSurfaces],
      missingRuntimeCapabilities: [...feature.missingRuntimeCapabilities],
      notes: [...feature.notes],
    })),
    summary: buildSummary(FEATURES),
  };
}

function buildSummary(features: ParityFeature[]): ParityReport["summary"] {
  const byStatus = Object.fromEntries(PARITY_STATUSES.map((status) => [status, 0])) as Record<ParityStatus, number>;
  const byCategory = Object.fromEntries(PARITY_CATEGORIES.map((category) => [category, "planned"])) as Record<ParityCategory, ParityStatus>;
  const missingCommandSurfaces = new Set<string>();
  const missingRuntimeCapabilities = new Set<string>();

  for (const feature of features) {
    byStatus[feature.status] += 1;
    byCategory[feature.category] = feature.status;
    for (const command of feature.missingCommandSurfaces) missingCommandSurfaces.add(command);
    for (const capability of feature.missingRuntimeCapabilities) missingRuntimeCapabilities.add(capability);
  }

  return {
    total: features.length,
    byStatus,
    byCategory,
    missingCommandSurfaces: OPENCODE_MISSING_COMMAND_SURFACES.filter((command) => missingCommandSurfaces.has(command)),
    missingRuntimeCapabilities: Array.from(missingRuntimeCapabilities).sort(),
    recommendedNextMilestone: RECOMMENDED_NEXT_MILESTONE,
  };
}
