import {
  PARITY_CATEGORIES,
  PARITY_STATUSES,
  type ParityCategory,
  type ParityFeature,
  type ParityReport,
  type ParityStatus,
} from "../../../shared/src/types/parity.js";

export const OPENCODE_MISSING_COMMAND_SURFACES = [
  "run",
  "serve",
  "web",
  "attach",
  "session",
  "export",
  "import",
  "providers",
  "models",
  "mcp",
  "agent",
  "plugin",
  "stats",
  "db",
  "github",
  "pr",
  "acp",
] as const;

const RECOMMENDED_NEXT_MILESTONE = "Milestone 1: Rust Runtime Authority For All Command Paths";

const FEATURES: ParityFeature[] = [
  {
    category: "runtime",
    surface: "Runtime authority",
    opencodeSurface: ["server/session/tool runtime", "event stream", "permission decisions"],
    dhSurface: ["Rust-hosted ask/explain/trace lifecycle", "TypeScript worker compatibility path"],
    status: "partial",
    priority: "P0",
    missingCommandSurfaces: [],
    missingRuntimeCapabilities: ["single Rust lifecycle authority for lane, run, session, provider, MCP, and tool paths"],
    nextMilestone: RECOMMENDED_NEXT_MILESTONE,
    notes: ["Rust is authoritative for first-wave knowledge commands only."],
  },
  {
    category: "cli",
    surface: "CLI command surface",
    opencodeSurface: [
      "run",
      "serve",
      "web",
      "attach",
      "session",
      "export",
      "import",
      "providers",
      "models",
      "mcp",
      "agent",
      "plugin",
      "stats",
      "db",
      "github",
      "pr",
      "acp",
    ],
    dhSurface: [
      "ask",
      "explain",
      "trace",
      "index",
      "doctor",
      "quick",
      "delivery",
      "migrate",
      "config",
      "semantic-cleanup",
      "operator-safe-maintenance",
    ],
    status: "partial",
    priority: "P0",
    missingCommandSurfaces: [...OPENCODE_MISSING_COMMAND_SURFACES],
    missingRuntimeCapabilities: ["OpenCode-like direct interactive run loop", "headless server command surface", "session import/export UX"],
    nextMilestone: "Milestone 2: dh run Direct Interactive Loop",
    notes: ["Existing DH commands are useful but do not cover the OpenCode daily interactive surface."],
  },
  {
    category: "session",
    surface: "Session product lifecycle",
    opencodeSurface: ["session list", "session delete", "continue", "fork", "export", "import", "share", "stats"],
    dhSurface: ["session primitives", "workflow state", "SQLite repositories"],
    status: "partial",
    priority: "P0",
    missingCommandSurfaces: ["session", "export", "import", "stats"],
    missingRuntimeCapabilities: ["stable cross-command resume/fork contract", "session event stream", "product-level session commands"],
    nextMilestone: "Milestone 3: Session Product Parity",
    notes: ["Session storage exists, but product-level parity is not exposed."],
  },
  {
    category: "provider",
    surface: "Provider and model lifecycle",
    opencodeSurface: ["providers list/login/logout", "models", "models.dev refresh"],
    dhSurface: ["AI SDK provider registry", "legacy provider/model listing"],
    status: "partial",
    priority: "P0",
    missingCommandSurfaces: ["providers", "models"],
    missingRuntimeCapabilities: ["credential lifecycle", "provider verification", "model refresh"],
    nextMilestone: "Milestone 4: Provider And Model Lifecycle",
    notes: ["Provider adapters exist; operator auth and refresh UX remain incomplete."],
  },
  {
    category: "mcp",
    surface: "MCP lifecycle",
    opencodeSurface: ["mcp add", "mcp list", "mcp auth", "mcp logout", "mcp debug", "OAuth callback"],
    dhSurface: ["MCP routing", "MCP auth status", "audit surfaces"],
    status: "partial",
    priority: "P1",
    missingCommandSurfaces: ["mcp"],
    missingRuntimeCapabilities: ["first-class MCP management commands", "OAuth callback handling", "runtime MCP server lifecycle"],
    nextMilestone: "Milestone 5: MCP Lifecycle",
    notes: ["Routing and status hardening exist; command lifecycle parity remains open."],
  },
  {
    category: "tool",
    surface: "Tool runtime catalog",
    opencodeSurface: ["read", "write", "edit", "bash", "glob", "grep", "apply_patch", "task", "todo", "webfetch", "websearch", "lsp"],
    dhSurface: ["retrieval tools", "bridge tools", "audit/enforcement records"],
    status: "partial",
    priority: "P1",
    missingCommandSurfaces: [],
    missingRuntimeCapabilities: ["OpenCode-equivalent tool schemas", "permission prompts", "streaming tool output", "tool result envelopes"],
    nextMilestone: "Milestone 6: Tool Runtime And Permissions",
    notes: ["DH has enforcement primitives but not an OpenCode-equivalent runtime catalog."],
  },
  {
    category: "agent",
    surface: "Agent and subagent runtime",
    opencodeSurface: ["agent create", "agent list", "task subagent", "build/plan/general agents"],
    dhSurface: ["workflow lanes", "role registry", "team roles"],
    status: "partial",
    priority: "P1",
    missingCommandSurfaces: ["agent"],
    missingRuntimeCapabilities: ["runtime agent registry", "subagent task delegation", "agent selection in run loop"],
    nextMilestone: "Milestone 7: Agent/Subagent Runtime",
    notes: ["DH roles can map into agents, but the runtime agent surface is not exposed."],
  },
  {
    category: "lsp",
    surface: "LSP graph augmentation",
    opencodeSurface: ["diagnostics", "hover", "definition", "references", "workspace symbols", "call hierarchy"],
    dhSurface: ["Rust structural graph", "semantic retrieval"],
    status: "planned",
    priority: "P2",
    missingCommandSurfaces: [],
    missingRuntimeCapabilities: ["LSP client service", "diagnostics tool", "symbol operation tools"],
    nextMilestone: "Milestone 8: LSP Graph Augmentation",
    notes: ["Rust graph remains the base; LSP should augment it rather than replace it."],
  },
  {
    category: "plugin",
    surface: "Plugin ecosystem",
    opencodeSurface: ["server hooks", "TUI hooks", "command hooks", "tool hooks", "chat hooks", "session hooks"],
    dhSurface: ["extension-state fingerprint", "drift reporting", "minimal plugin contract docs"],
    status: "planned",
    priority: "P2",
    missingCommandSurfaces: ["plugin"],
    missingRuntimeCapabilities: ["server plugin API", "deterministic hook order", "bounded compatibility contract"],
    nextMilestone: "Milestone 9: Plugin MVP",
    notes: ["Existing extension observability is not a plugin ecosystem."],
  },
  {
    category: "server",
    surface: "Headless server and SDK",
    opencodeSurface: ["serve", "SDK client/server architecture"],
    dhSurface: [],
    status: "planned",
    priority: "P2",
    missingCommandSurfaces: ["serve"],
    missingRuntimeCapabilities: ["local HTTP/WebSocket server", "session/event/provider/MCP APIs", "SDK client"],
    nextMilestone: "Milestone 10: Server/SDK",
    notes: ["Server should build on the run/session/event contract after it is stable."],
  },
  {
    category: "tui",
    surface: "Terminal UI",
    opencodeSurface: ["OpenTUI interactive client", "attach"],
    dhSurface: [],
    status: "planned",
    priority: "P2",
    missingCommandSurfaces: ["attach"],
    missingRuntimeCapabilities: ["TUI client", "permission UI", "model/agent switch UI", "session attachment"],
    nextMilestone: "Milestone 11: TUI MVP",
    notes: ["TUI should attach to the same event stream as dh run and server."],
  },
  {
    category: "github",
    surface: "GitHub and PR automation",
    opencodeSurface: ["github", "pr import", "pr checkout"],
    dhSurface: [],
    status: "deferred",
    priority: "P3",
    missingCommandSurfaces: ["github", "pr"],
    missingRuntimeCapabilities: ["GitHub auth", "PR import/checkout workflow", "GitHub agent integration"],
    nextMilestone: "Milestone 12: GitHub/PR Automation",
    notes: ["This depends on session import/export and provider/tool runtime stability."],
  },
  {
    category: "packaging",
    surface: "Desktop/cloud console",
    opencodeSurface: ["desktop package", "console package", "cloud/provider account surfaces"],
    dhSurface: ["local CLI release assets"],
    status: "out_of_scope",
    priority: "P3",
    missingCommandSurfaces: [],
    missingRuntimeCapabilities: ["desktop app", "cloud console", "remote share service"],
    nextMilestone: "No milestone until local/server/TUI surfaces prove stable",
    notes: ["This is intentionally outside the first parity program."],
  },
];

export function buildOpenCodeParityReport(): ParityReport {
  return {
    source: "opencode-gap-roadmap",
    baseline: {
      dh: "v0.3.1-rc.7 / 506b0af",
      opencode: "dev / 903d81819",
    },
    categories: PARITY_CATEGORIES,
    statuses: PARITY_STATUSES,
    features: FEATURES.map((feature) => ({
      ...feature,
      opencodeSurface: [...feature.opencodeSurface],
      dhSurface: [...feature.dhSurface],
      missingCommandSurfaces: [...feature.missingCommandSurfaces],
      missingRuntimeCapabilities: [...feature.missingRuntimeCapabilities],
      notes: [...feature.notes],
    })),
    summary: buildSummary(FEATURES),
  };
}

function buildSummary(features: ParityFeature[]): ParityReport["summary"] {
  const byStatus = Object.fromEntries(PARITY_STATUSES.map((status) => [status, 0])) as Record<ParityStatus, number>;
  const byCategory = Object.fromEntries(PARITY_CATEGORIES.map((category) => [category, "planned"])) as Record<ParityCategory, ParityStatus>;
  const missingCommandSurfaces = new Set<string>();
  const missingRuntimeCapabilities = new Set<string>();

  for (const feature of features) {
    byStatus[feature.status] += 1;
    byCategory[feature.category] = feature.status;
    for (const command of feature.missingCommandSurfaces) missingCommandSurfaces.add(command);
    for (const capability of feature.missingRuntimeCapabilities) missingRuntimeCapabilities.add(capability);
  }

  return {
    total: features.length,
    byStatus,
    byCategory,
    missingCommandSurfaces: OPENCODE_MISSING_COMMAND_SURFACES.filter((command) => missingCommandSurfaces.has(command)),
    missingRuntimeCapabilities: Array.from(missingRuntimeCapabilities).sort(),
    recommendedNextMilestone: RECOMMENDED_NEXT_MILESTONE,
  };
}
