export const Flag = {
  OPENCODE_MODELS_URL: process.env.OPENCODE_MODELS_URL,
  OPENCODE_MODELS_PATH: process.env.OPENCODE_MODELS_PATH,
  OPENCODE_DISABLE_MODELS_FETCH: process.env.OPENCODE_DISABLE_MODELS_FETCH,
  OPENCODE_LOG_LEVEL: process.env.OPENCODE_LOG_LEVEL,
  OPENCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX: process.env.OPENCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX ? Number(process.env.OPENCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX) : undefined,
};
